name: detekt_checker
on:
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Detekt Lint
        run: |
          cd book-manager && ./gradlew detekt

      - name: Check whether if error found
        run: |
          cat book-manager/build/reports/detekt/detekt.txt |\
           wc -l | awk '$0 != 0 {exit 1}'
